### ISSUE TITLE
[Bug]: Unable to find component: [stephenjude.filament-two-factor-authentication.pages.login]

### ISSUE THREAD

**Issue by Lorraine-Olegario** [stephenjude/filament-two-factor-authentication#3]
### Current behavior:
I receive the error:
`Unable to find component: [stephenjude.filament-two-factor-authentication.pages.login]`

This indicates that the package is trying to load a login component that does not exist at the expected path 

### Expected behavior:
The login page should load correctly, or the login component should exist in the installed package.

### Steps to reproduce the problem:
1. Installed the `stephenjude/filament-two-factor-authentication` package.
2. Followed the documentation to add two-factor authentication in Filament.
3. Configured `TwoFactorAuthenticatable` and the plugin as instructed.

### Actions taken:
- I attempted to manually create the `login` page in `resources/views/vendor/filament-two-factor-authentication/pages`, but the error persists.
- If I deactivate the plugin and log in, then reactivate it, I can configure it. The error only occurs when trying to log in.

### Package Version

0.0.4

### PHP Version

8.3.4

### Laravel Version

11.21

### Which operating systems does with happen with?

Windows

### Notes

![Captura de tela 2024-09-19 210017](https://github.com/user-attachments/assets/f021670f-e599-4a02-b6a3-408f552b9c87)

**Comment by stephenjude** [comment]
We are currently using this @pay4me and it's running on Laravel 11 and PHP 8.3.

Let me try and replicate this and get back to you.

**Comment by stephenjude** [comment]
@Lorraine-Olegario I think the issue here is that livewire component registration is not working as expected. I will drill into this more in my free time.

**Comment by Asfand-php** [comment]
there are a lot more issues with this , now my filament User models is broken, did some digging and its related to // public function canAccessPanel(Panel $panel): bool{
        //     return $this->user_type === self::USER_TYPE_OWNER;
        // }
        
        spend 2 days making it work and its still broken .

**Comment by stephenjude** [comment]
@Lorraine-Olegario I am not able to replicate this issue. I will be closing this issue.
